TELFE 104: review and update readme
telicent-oss/telicent-access pull request #11
Opened 2024-06-28 15:39 UTC by AlecsMissangu

Added docker setup and teardown scripts which are referenced in the getting started section of the README.md
Created DEVELOPMENT.md for a better separation of concerns

Ticket: [TELFE-104](https://telicent.atlassian.net/browse/TELFE-104)

2024-07-01 08:45 UTC, davec504 approved these changes

2024-07-01 08:45 UTC, davec504 commented on README.md
>  When deployed with its basic functionality (SCIM_ENABLED = false), ACCESS is simply
Question: Didn't SCIM get ripped out?

2024-07-01 08:45 UTC, davec504 commented on README.md
> +<!-- ### Users
Question: Should this be removed?

2024-07-01 09:01 UTC, AlecsMissangu commented on README.md
>  When deployed with its basic functionality (SCIM_ENABLED = false), ACCESS is simply
I don't know

2024-07-01 09:02 UTC, AlecsMissangu commented on README.md
> +<!-- ### Users
Yes, it's no longer relevant. I will send you the thread of MS chat from the FE group chat

2024-07-01 09:51 UTC, ACoolmanTelicent commented on README.md
>  When deployed with its basic functionality (SCIM_ENABLED = false), ACCESS is simply
The code [seems to exist](https://github.com/search?q=repo%3Atelicent-oss%2Ftelicent-access%20SCIM&type=code), but I recall @tatelicent saying it may leave.

2024-07-02 08:14 UTC, ACoolmanTelicent requested changes
2 config requests

2024-07-02 08:14 UTC, ACoolmanTelicent commented on scripts/open-ui.py
> +open_browser(url)
Lets replace this python script with a one-liner shellscript
```sh
open http://localhost:8080/access
```

2024-07-02 08:14 UTC, ACoolmanTelicent commented on docker-compose.yaml
> +        condition: service_healthy
I like this health check technique, but perhaps not worth using it to delay FE builds at this time

2024-07-02 15:10 UTC, ACoolmanTelicent approved these changes

2024-07-02 15:11 UTC, ACoolmanTelicent commented on scripts/open-ui.py
> +open_browser(url)
Note: Not a blocker

but I mean literally delete `open-ui.py`

And create `open-ui.sh`


```
#!/usr/bin/env sh
set -e
open http://localhost:8080/access
```

2024-07-03 09:15 UTC, davec504 approved these changes

2024-07-08 08:18 UTC, merged